variable "web_app_name" {}
variable "github_repository_url" {}
variable "codecommit_repository_url" {}
variable "codecommit_git_credential" {}
variable "codecommit_iam_username" {}
variable "codecommit_iam_password" {}
variable "domain_name" {}
variable "app_branch" {}
variable "cognito_arn" {}